CUDA_VISIBLE_DEVICES="1" python run_BERT_RE_finetuning.py \
    --output_dir=output/RE_Bert/v2 \
    --model_name_or_path=data/pre-trained_models/tiny-bert/2nd_General_TinyBERT_4L_312D \
    --model_type=REBERT \
    --do_train \
    --data_dir=data/wikitables_v2 \
    --evaluate_during_training \
    --per_gpu_train_batch_size=20 \
    --per_gpu_eval_batch_size=20 \
    --gradient_accumulation_steps=2 \
    --learning_rate=5e-5 \
    --num_train_epochs=25 \
    --save_total_limit=10 \
    --seed=1 \
    --cache_dir=cache \
    --overwrite_output_dir \
    --config_name=configs/tiny-bert-config.json \
    --save_steps=500 \
    --logging_steps=250 > /dev/null 2>&1 &
